name: finenot
description: FinEnot — менеджер кредитов/микрозаймов. Flutter‑порт.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.6.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_local_notifications: ^17.2.2
  local_auth: ^2.1.6
  flutter_secure_storage: ^9.0.0
  intl: ^0.19.0
  collection: ^1.18.0
  lottie: ^2.6.0
  fl_chart: ^0.63.0
  path_provider: ^2.1.1
  file_picker: ^8.0.0+1
  share_plus: ^7.2.1
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.7
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/lottie/
    - assets/data/
